### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fbjork** [binaryseed/new_relic_ecto#1]
@binaryseed Any plans on making an initial version that works?

**Comment by binaryseed** [comment]
heh, at this point I don't have a plan. I want this to leverage Ecto 3's integration with Telemetry 

https://github.com/beam-telemetry/telemetry

Open to suggestions / contributions since I don't use ecto in my main elixir project (it's stateless)

**Comment by binaryseed** [comment]
I've started working on the project :)

**Comment by fbjork** [comment]
@binaryseed any plans on releasing a working version of this library any time soon?
